# Generated by Django 4.0.1 on 2022-05-24 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('height', models.PositiveSmallIntegerField(verbose_name='height')),
                ('width', models.PositiveSmallIntegerField(verbose_name='width')),
            ],
            options={
                'verbose_name': 'candle',
                'verbose_name_plural': 'candles',
            },
        ),
        migrations.CreateModel(
            name='CandleForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('hex_code', models.CharField(max_length=50, verbose_name='hex code')),
            ],
            options={
                'verbose_name': 'color',
                'verbose_name_plural': 'colors',
            },
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'composition',
                'verbose_name_plural': 'compositions',
            },
        ),
        migrations.CreateModel(
            name='Smell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'smell',
                'verbose_name_plural': 'smells',
            },
        ),
        migrations.CreateModel(
            name='Wick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'wick',
                'verbose_name_plural': 'wicks',
            },
        ),
        migrations.CreateModel(
            name='CandleImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(upload_to='')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='candles.candle')),
            ],
        ),
        migrations.CreateModel(
            name='CandleFormImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(upload_to='')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='candles.candleform')),
            ],
        ),
        migrations.AddField(
            model_name='candle',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candles', to='candles.color', verbose_name='color'),
        ),
        migrations.AddField(
            model_name='candle',
            name='composition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candles', to='candles.composition', verbose_name='composition'),
        ),
        migrations.AddField(
            model_name='candle',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candles', to='candles.candleform', verbose_name='form'),
        ),
        migrations.AddField(
            model_name='candle',
            name='smell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candles', to='candles.smell', verbose_name='smell'),
        ),
        migrations.AddField(
            model_name='candle',
            name='wick',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candles', to='candles.wick', verbose_name='wick'),
        ),
    ]
